function str = getCbuilder(object)
    str = sprintf('HH_model(%e,%e,%e,%e,%e,%e,%e,%e,%e,%e,%e)',...
        object.gna,object.ENa,object.gk2,object.Ek,object.gl,object.El,...
        object.tNa,object.tk2,object.C,object.Iapp,object.VshiftK2);
end